//! Nous → JavaScript code generator.
//!
//! Compiles Nous AST directly to JavaScript source code.
//! The generated JS runs in any browser or Node.js environment.
//!
//! Mapping:
//!   fn         → function
//!   entity     → class with constructor
//!   let        → const
//!   if/then/else → ternary or if/else
//!   match      → switch-like if/else chain
//!   require    → if (!cond) throw
//!   ensure     → console.assert (dev mode)
//!   record     → object literal
//!   record update → Object.assign({}, base, updates)
//!   pipe       → nested function calls
//!   Ok/Err     → {ok: true, value} / {ok: false, error}
//!   ?          → unwrap helper

use nous_ast::decl::*;
use nous_ast::expr::*;
use nous_ast::program::Program;
use nous_ast::types::TypeExpr;

/// Compile a Nous Program to JavaScript source code.
pub fn compile_to_js(program: &Program) -> String {
    let mut out = String::new();
    out.push_str("// Generated by Nous compiler — do not edit\n");
    out.push_str("\"use strict\";\n\n");

    // Emit helpers
    out.push_str(JS_HELPERS);
    out.push('\n');

    for decl in &program.declarations {
        match &decl.node {
            Decl::Entity(e) => emit_entity(&mut out, e),
            Decl::Enum(e) => emit_enum(&mut out, e),
            Decl::Fn(f) => emit_fn(&mut out, f),
            Decl::Flow(f) => emit_flow(&mut out, f),
            Decl::Main(m) => emit_main(&mut out, m),
            Decl::Namespace(_) | Decl::Use(_) | Decl::Type(_)
            | Decl::State(_) | Decl::Effect(_) | Decl::Endpoint(_)
            | Decl::Handler(_) => {} // skip non-code declarations
        }
    }

    out
}

const JS_HELPERS: &str = r#"
function __ok(v) { return { ok: true, value: v }; }
function __err(e) { return { ok: false, error: e }; }
function __unwrap(r) {
  if (r && r.ok === true) return r.value;
  if (r && r.ok === false) throw new Error("unwrap Err: " + JSON.stringify(r.error));
  return r;
}
function __require(cond, msg) { if (!cond) throw new Error("require violated: " + msg); }
"#;

fn emit_entity(out: &mut String, e: &EntityDecl) {
    out.push_str(&format!("class {} {{\n", e.name));
    out.push_str("  constructor(fields) {\n");
    for field in &e.fields {
        out.push_str(&format!("    this.{} = fields.{};\n", field.node.name, field.node.name));
    }
    out.push_str("  }\n}\n\n");
}

fn emit_enum(out: &mut String, e: &EnumDecl) {
    out.push_str(&format!("const {} = {{\n", e.name));
    for variant in &e.variants {
        if variant.fields.is_empty() {
            out.push_str(&format!("  {}: {{ variant: \"{}\" }},\n", variant.name, variant.name));
        } else {
            let params: Vec<&str> = variant.fields.iter().map(|f| f.name.as_str()).collect();
            out.push_str(&format!(
                "  {}: ({}) => ({{ variant: \"{}\", {} }}),\n",
                variant.name,
                params.join(", "),
                variant.name,
                params.iter().map(|p| format!("{p}: {p}")).collect::<Vec<_>>().join(", ")
            ));
        }
    }
    out.push_str("};\n\n");
}

fn emit_fn(out: &mut String, f: &FnDecl) {
    let params: Vec<&str> = f.params.iter().map(|p| p.name.as_str()).collect();
    out.push_str(&format!("function {}({}) {{\n", f.name, params.join(", ")));

    // Emit requires
    for req in &f.contract.requires {
        let cond = expr_to_js(&req.condition.node);
        out.push_str(&format!("  __require({cond}, \"{}\");\n", escape_js(&cond)));
    }

    // Check if body is empty (synthesized function)
    let body_empty = matches!(&f.body.node, Expr::Void)
        || matches!(&f.body.node, Expr::Block(stmts) if stmts.is_empty());

    if body_empty && !f.contract.ensures.is_empty() {
        // Synthesize from ensures: find `result == expr` pattern
        for ensure in &f.contract.ensures {
            if let Some(expr) = extract_result_assignment(&ensure.node) {
                let js = expr_to_js(expr);
                out.push_str(&format!("  return {js};\n"));
                break;
            }
        }
    } else {
        // Compile body
        let body_js = expr_to_js(&f.body.node);
        if matches!(&f.body.node, Expr::Block(_)) {
            out.push_str(&body_js);
        } else {
            out.push_str(&format!("  return {body_js};\n"));
        }
    }

    // Emit ensures as assertions (dev mode)
    for ensure in &f.contract.ensures {
        let cond = expr_to_js(&ensure.node);
        out.push_str(&format!("  // ensure: {cond}\n"));
    }

    out.push_str("}\n\n");
}

fn emit_flow(out: &mut String, f: &FlowDecl) {
    let params: Vec<&str> = f.params.iter().map(|p| p.name.as_str()).collect();
    out.push_str(&format!("function {}({}) {{\n", f.name, params.join(", ")));
    out.push_str("  const __rollbacks = [];\n");
    out.push_str("  try {\n");

    for step in &f.steps {
        out.push_str(&format!("    // step: {}\n", step.name));
        let body_js = expr_to_js(&step.body.node);
        out.push_str(&format!("    const {}_result = {};\n", step.name, body_js));
        // Store rollback
        if !matches!(&step.rollback.node, Expr::Void) {
            let rb = expr_to_js(&step.rollback.node);
            out.push_str(&format!("    __rollbacks.push(() => {rb});\n"));
        }
    }

    if let Some(last) = f.steps.last() {
        out.push_str(&format!("    return __ok({}_result);\n", last.name));
    } else {
        out.push_str("    return __ok(undefined);\n");
    }

    out.push_str("  } catch(e) {\n");
    out.push_str("    for (let i = __rollbacks.length - 1; i >= 0; i--) __rollbacks[i]();\n");
    out.push_str("    return __err(e.message || String(e));\n");
    out.push_str("  }\n");
    out.push_str("}\n\n");
}

fn emit_main(out: &mut String, m: &MainDecl) {
    out.push_str("// ── Main ────────────────────────────\n");
    out.push_str("const __result = (function() {\n");
    let body_js = expr_to_js(&m.body.node);
    if matches!(&m.body.node, Expr::Block(_)) {
        out.push_str(&body_js);
    } else {
        out.push_str(&format!("  return {body_js};\n"));
    }
    out.push_str("})();\n");
    out.push_str("if (typeof __result !== 'undefined') console.log(__result);\n");
}

// ── Expression → JS ──────────────────────────────────

fn expr_to_js(expr: &Expr) -> String {
    match expr {
        Expr::IntLit(n) => n.to_string(),
        Expr::DecLit(s) => s.clone(),
        Expr::StringLit(s) => format!("\"{}\"", escape_js(s)),
        Expr::BoolLit(b) => b.to_string(),
        Expr::Void => "undefined".to_string(),
        Expr::SelfRef => "this".to_string(),

        Expr::Ident(name) => name.clone(),

        Expr::FieldAccess { object, field } => {
            format!("{}.{field}", expr_to_js(&object.node))
        }

        Expr::BinOp { op, left, right } => {
            let l = expr_to_js(&left.node);
            let r = expr_to_js(&right.node);
            let op_str = match op {
                BinOp::Add => "+", BinOp::Sub => "-",
                BinOp::Mul => "*", BinOp::Div => "/",
                BinOp::Mod => "%",
                BinOp::Eq => "===", BinOp::Neq => "!==",
                BinOp::Lt => "<", BinOp::Lte => "<=",
                BinOp::Gt => ">", BinOp::Gte => ">=",
                BinOp::And => "&&", BinOp::Or => "||",
                BinOp::Implies => return format!("(!({l}) || ({r}))"),
            };
            format!("({l} {op_str} {r})")
        }

        Expr::UnaryOp { op, operand } => {
            let inner = expr_to_js(&operand.node);
            match op {
                UnaryOp::Neg => format!("(-{inner})"),
                UnaryOp::Not => format!("(!{inner})"),
            }
        }

        Expr::Call { func, args } => {
            let f = expr_to_js(&func.node);
            let a: Vec<String> = args.iter().map(|a| expr_to_js(&a.node)).collect();
            format!("{f}({})", a.join(", "))
        }

        Expr::Pipe { value, func, args } => {
            let v = expr_to_js(&value.node);
            let f = expr_to_js(&func.node);
            let mut all_args = vec![v];
            all_args.extend(args.iter().map(|a| expr_to_js(&a.node)));
            format!("{f}({})", all_args.join(", "))
        }

        Expr::Try(inner) => {
            format!("__unwrap({})", expr_to_js(&inner.node))
        }

        Expr::Let { pattern, value, .. } => {
            let val = expr_to_js(&value.node);
            match &pattern.node {
                Pattern::Ident(name) => format!("const {name} = {val}"),
                Pattern::Wildcard => val,
                _ => format!("const _pat = {val}"),
            }
        }

        Expr::Block(stmts) => {
            let mut lines = Vec::new();
            for (i, stmt) in stmts.iter().enumerate() {
                let js = expr_to_js(&stmt.node);
                if i == stmts.len() - 1 && !matches!(&stmt.node, Expr::Let { .. } | Expr::Require { .. }) {
                    lines.push(format!("  return {js};"));
                } else {
                    lines.push(format!("  {js};"));
                }
            }
            lines.join("\n") + "\n"
        }

        Expr::If { condition, then_branch, else_branch } => {
            let cond = expr_to_js(&condition.node);
            let then_js = expr_to_js(&then_branch.node);
            if let Some(else_br) = else_branch {
                let else_js = expr_to_js(&else_br.node);
                format!("({cond} ? {then_js} : {else_js})")
            } else {
                format!("({cond} ? {then_js} : undefined)")
            }
        }

        Expr::Match { scrutinee, arms } => {
            let scrut = expr_to_js(&scrutinee.node);
            let mut js = format!("(function() {{ const __m = {scrut};\n");
            for arm in arms {
                let (test, bindings) = pattern_to_js_test(&arm.pattern.node, "__m");
                let body = expr_to_js(&arm.body.node);
                if test == "true" {
                    js.push_str(&format!("  {bindings}return {body};\n"));
                } else {
                    js.push_str(&format!("  if ({test}) {{ {bindings}return {body}; }}\n"));
                }
            }
            js.push_str("  throw new Error('non-exhaustive match');\n");
            js.push_str("})()");
            js
        }

        Expr::Record { name, fields } => {
            let props: Vec<String> = fields
                .iter()
                .map(|(k, v)| format!("{k}: {}", expr_to_js(&v.node)))
                .collect();
            format!("new {}({{ {} }})", name, props.join(", "))
        }

        Expr::RecordUpdate { base, updates } => {
            let base_js = expr_to_js(&base.node);
            let props: Vec<String> = updates
                .iter()
                .map(|(k, v)| format!("{k}: {}", expr_to_js(&v.node)))
                .collect();
            format!("Object.assign({{}}, {base_js}, {{ {} }})", props.join(", "))
        }

        Expr::Ok(inner) => format!("__ok({})", expr_to_js(&inner.node)),
        Expr::Err(inner) => format!("__err({})", expr_to_js(&inner.node)),

        Expr::List(items) => {
            let elems: Vec<String> = items.iter().map(|i| expr_to_js(&i.node)).collect();
            format!("[{}]", elems.join(", "))
        }

        Expr::Tuple(items) => {
            let elems: Vec<String> = items.iter().map(|i| expr_to_js(&i.node)).collect();
            format!("[{}]", elems.join(", "))
        }

        Expr::Lambda { params, body } => {
            let p: Vec<&str> = params.iter().map(|p| p.name.as_str()).collect();
            let b = expr_to_js(&body.node);
            format!("({}) => {b}", p.join(", "))
        }

        Expr::Return(inner) => format!("return {}", expr_to_js(&inner.node)),

        Expr::Require { condition, else_expr } => {
            let cond = expr_to_js(&condition.node);
            format!("__require({cond}, \"{}\")", escape_js(&cond))
        }

        Expr::Transaction(inner) => expr_to_js(&inner.node),
        Expr::Primed(inner) => format!("{}_prime", expr_to_js(&inner.node)),
        Expr::Pre(inner) => format!("__pre_{}", expr_to_js(&inner.node)),
    }
}

fn pattern_to_js_test(pattern: &Pattern, scrutinee: &str) -> (String, String) {
    match pattern {
        Pattern::Wildcard => ("true".to_string(), String::new()),
        Pattern::Ident(name) => ("true".to_string(), format!("const {name} = {scrutinee}; ")),
        Pattern::Constructor { name, fields } => {
            match name.as_str() {
                "Ok" => {
                    let binding = if let Some(inner) = fields.first() {
                        if let Pattern::Ident(n) = &inner.node {
                            format!("const {n} = {scrutinee}.value; ")
                        } else { String::new() }
                    } else { String::new() };
                    (format!("{scrutinee} && {scrutinee}.ok === true"), binding)
                }
                "Err" => {
                    let binding = if let Some(inner) = fields.first() {
                        if let Pattern::Ident(n) = &inner.node {
                            format!("const {n} = {scrutinee}.error; ")
                        } else { String::new() }
                    } else { String::new() };
                    (format!("{scrutinee} && {scrutinee}.ok === false"), binding)
                }
                _ => {
                    (format!("{scrutinee} && {scrutinee}.variant === \"{name}\""), String::new())
                }
            }
        }
        Pattern::Literal(expr) => {
            let val = expr_to_js(expr);
            (format!("{scrutinee} === {val}"), String::new())
        }
        Pattern::Tuple(_) => ("true".to_string(), String::new()),
    }
}

fn extract_result_assignment(expr: &Expr) -> Option<&Expr> {
    if let Expr::BinOp { op: BinOp::Eq, left, right } = expr {
        if matches!(&left.node, Expr::Ident(n) if n == "result") {
            return Some(&right.node);
        }
        if matches!(&right.node, Expr::Ident(n) if n == "result") {
            return Some(&left.node);
        }
    }
    None
}

fn escape_js(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n")
}
